name: generate bundles

on: [push]

jobs:

  call-win_base:
    uses: ./.github/workflows/win_base.yml
    with:
      win-architecture: 'x64'
    secrets: 
      token: ${{ secrets.GITHUB_TOKEN }}

    - name: Put current date into a variable
      run: |
        $DATE=& Get-Date -format yyyy-MM-dd
        echo "DATE=$DATE" >> $env:GITHUB_ENV