name: generate bundles

on: [push]

jobs:

  call-win_base:
    uses: ./.github/workflows/win_base.yml
    with:
      win-architecture: 'x64'
    secrets: 
      token: ${{ secrets.GITHUB_TOKEN }}

    - name: Put current date into a variable
      run: |
        $DATE=& Get-Date -format yyyy-MM-dd
        echo "DATE=$DATE" >> $env:GITHUB_ENV

    - name: Put current commit hash in a variable
      run: |
        $COMMIT=$(git rev-parse HEAD)
        echo "COMMIT=$COMMIT" >> $env:GITHUB_ENV
        
    - name: Upgrade pip and enable wheel support
      run: python -m pip install --upgrade pip setuptools wheel 

    - name: Install InVesalius requirements
      run: pip install -r requirements.txt

    - name: Compile InVesalius Cython parts
      run: |
            python3 setup.py build_ext --inplace
            python3 setup.py build_plugins

    - name: Insert version and commit hash into dialog.py
      run: python3 bundle_tools/win/insert_version_date.py ./invesalius/gui/dialogs.py ${{ env.DATE }} ${{ env.COMMIT }} nightly